title: Catholic High School
url: https://catholichigh.moe.edu.sg
favicon: /images/chslogo1.png
colors:
  primary-color: "#26691c"
  secondary-color: "#26691c"
  media-colors:
    - title: media-color-one
      color: "#5f8d4e"
    - title: media-color-two
      color: "#5f8d4e"
    - title: media-color-three
      color: "#a4be7b"
    - title: media-color-four
      color: "#a4be7b"
    - title: media-color-five
      color: "#a4be7b"
description: Catholic High School
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d26k7rl81eo6rb.amplifyapp.com
prod: https://master.d26k7rl81eo6rb.amplifyapp.com
shareicon: /images/chslogo1.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: resources
